if !empty(system("setxkbmap -print|grep bepo"))
    source ~/.vimrc.bepo
endif

let file = expand("~/.vim/autoload/pathogen.vim")
if filereadable(file)
    execute pathogen#infect()
endif

" Leader - ( Spacebar )
let mapleader = " "

" Global settings
set nocompatible
set hlsearch
set cursorline
set title

set background=dark

set shiftwidth=4
set expandtab
set tabstop=4

syntax on

" Start scrolling when we are 3 lines away from margins
set scrolloff=3

" Open new split panes to right and bottom
set splitbelow
set splitright

" Auto resize Vim splits to active split
set winwidth=84
set winheight=5
set winminheight=5
set winheight=999

" Resize panes
nnoremap <silent> <C-Right> :vertical resize +5<cr>
nnoremap <silent> <C-Left> :vertical resize -5<cr>
nnoremap <silent> <C-Up> :resize +5<cr>
nnoremap <silent> <C-Down> :resize -5<cr>

" Quicker window movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" Switch between the last two files
nnoremap <leader><leader> <c-^>

" Quickly slect buffer
nnoremap <leader>bb :buffers<CR>:buffer<Space>
nnoremap <leader>bn :bn<CR>
nnoremap <leader>bp :bp<CR>

" Show line numbers
highlight LineNr term=bold ctermfg=darkgray guifg=darkgray

" Toggle relative numbering, set to absolute on loss of focus or insert mode
set nu!
set rnu
function! ToggleNumberOn()
    set nu!
    set rnu
endfunction
function! ToggleRelativeOn()
    set rnu!
    set nu
endfunction

autocmd FocusLost * call ToggleRelativeOn()
autocmd FocusGained * call ToggleNumberOn()
autocmd InsertEnter * call ToggleRelativeOn()
autocmd InsertLeave * call ToggleNumberOn()

" Switch relative <-> absolute numbering
nnoremap <leader>t :call ToggleRelativeOn()<cr>
nnoremap <leader>r :call ToggleNumberOn()<cr>

" Special configuration for development
filetype on
autocmd FileType .c,.cpp,.cxx,.h set cindent|set cin|set softtabstop=4
set smartindent

" Does not expand type for makefiles
autocmd FileType make setlocal noexpandtab

" Special highlighting for Doxygen
let g:load_doxygen_syntax=1

" Enable saving a file when forgot to sudo
cmap w!! w !sudo tee % >/dev/null

" Quick way to enable spell check
cmap s!! set spell spelllang=

" Use hjkl
nnoremap <Left> :echoe "Use h you NOOB!"<CR>
nnoremap <Right> :echoe "Use l you NOOB!"<CR>
nnoremap <Up> :echoe "Use k you NOOB!"<CR>
nnoremap <Down> :echoe "Use j you NOOB!"<CR>

" Stop current highlighting
nnoremap <leader>h :noh<cr>


" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
      command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
              \ | wincmd p | diffthis
endif

" Plugins specific
" NERDTree
map <C-n> :NERDTreeToggle<cr>
