#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export VISUAL=vim
export EDITOR=vim
export LANG=en_US.UTF-8
export LD_LIBRARY_PATH=/usr/local/lib

if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi

alias ls='ls --color=auto'

PS1='[\u@\h \W]\$ '
